### ISSUE TITLE
Can a parameter be added to set the "Notes for certification"?

### ISSUE THREAD

**Issue by jermowery** [wdzeng/edge-addon#10]
Simple FR, can a new parameter be added for setting the "Notes for certification" as described here (https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?tabs=v1-1#publishing-the-submission).

Sometimes the Microsoft reviews are very particular about an extension update having these notes

**Comment by jermowery** [comment]
This *looks* simple to add here: https://github.com/wdzeng/edge-addon/blob/main/src/lib.ts#L127

but obviously I am not as familiar with the source code or the releasing process for this workflow

**Comment by jermowery** [comment]
I will just send a PR to do this

**Comment by wdzeng** [comment]
Landed on v2.1.0. Thanks!
