### ISSUE TITLE
401 error on 'Uploading package'

### ISSUE THREAD

**Issue by adamlui** [wdzeng/edge-addon#13]
I don't know why, manual upload resulted in no errors. I use this Action across several repos without problem. Here is the log:

https://github.com/adamlui/perplexity-omnibox/actions/runs/12525262490/job/34936653752

![image](https://github.com/user-attachments/assets/96469ae8-ee38-478e-90af-da268003949b)

Here is the workflow: https://github.com/adamlui/perplexity-omnibox/blob/main/.github/workflows/publish-to-cws-ews-on-chromium-bump.yml

It is identical to this working workflow https://github.com/adamlui/brave-omnibox/blob/main/.github/workflows/publish-to-cws-ews-on-chromium-bump.yml

Working workflow last ran successfully last week https://github.com/adamlui/brave-omnibox/actions/runs/12389275932/job/34581966164 (although it does wait and wait after publish step but at least gets past upload):

![image](https://github.com/user-attachments/assets/c7e32cad-208f-46a7-ac3a-f96a1cc8f8c0)

Source code + repo structure for brave-omnibox that experiences working run is 99% identical to perplexity-omnibox that experiences failure, also I believe it succeeded before due to I recall mentally classifying workflow as polished and ready for production

**Comment by wdzeng** [comment]
Hi, 401 indicates something wrong during the authentication. Did you check your credentials?

**Comment by adamlui** [comment]
I did re-paste the same secrets in Actions secrets but how do you use cmd line or URL bar to check?

**Comment by adamlui** [comment]
IDK man all the version bump commits linked above are result in 401 now, that latest one even succeeded mere 2 days ago https://github.com/adamlui/chatgpt-auto-continue/actions/runs/12506968057 yet neither workflow nor Actions secrets were edited since

**Comment by wdzeng** [comment]
The error message did tell you the reason.

![IMG_0046](https://github.com/user-attachments/assets/011ee508-843a-445c-a08a-f5fc6cfd97e2)

**Comment by adamlui** [comment]
That's not the error this issue pertains to (401 means does not get past the upload step)

**Comment by adamlui** [comment]
You clicked a run that did not 401, which is now the new behavior (extension in progress is desired error and got past upload at least)

**Comment by adamlui** [comment]
I only linked to it to show you the recency of it working (it says 2 days ago, all these 401s started happening yesterday)

**Comment by adamlui** [comment]
If you click on any of the bump commits I just made in this issue's timeline (except ai-web-extensions because that one doesn't have workflow) > green checkmark > Publish to CWS + EWS on Chromium version bump > Publish to EWS step,  it will all show 401

**Comment by adamlui** [comment]
Manual publish works so do Edge secrets expire?

**Comment by wdzeng** [comment]
I'm not sure. But I would suggest you re-generate a new credential and retry the workflow.

**Comment by adamlui** [comment]
So you don't know how to test from cmd line right?

**Comment by adamlui** [comment]
Also I noticed the log says v1 did that get deprecated?

**Comment by wdzeng** [comment]
> So you don't know how to test from cmd line right?

Did you mean run a workflow via CLI? IDK.

**Comment by adamlui** [comment]
Check it out I think the timing is no coincidence

![Screenshot_20241228-111456](https://github.com/user-attachments/assets/fcc244fa-d459-4240-ab64-580d608dec4e)

**Comment by adamlui** [comment]
The answer is AI so it could've been December 28 maybe

**Comment by wdzeng** [comment]
> Also I noticed the log says v1 did that get deprecated?

Action @v1 maps to the edge API v1.0. It's deprecated and I'm not sure when Microsoft will drop it. But you are using @v2 so you should not worry about this.

**Comment by adamlui** [comment]
But log shows Action v2 uses Edge v1 and my bing screenshot shows Edge v1 support ends at end of December, and it is now end of December, and Edge secrets shouldn't expire, you don't think it's related?

**Comment by adamlui** [comment]
Shouldnt log show v1.1 not v1 if your upgrade worked?

**Comment by wdzeng** [comment]
My opinion: v1 is the collection of v1.x, so v1 could be v1.0 or v1.1.

You can look at the source code and you'll know this action is now using v1.1.

**Comment by adamlui** [comment]
I also thought that's possible, but look again at the screenshot sourced from official Microsoft doc

![image](https://github.com/user-attachments/assets/8ebb1781-8222-4343-a1c6-850b10ed210a)

See it explicitly refers to old one as 'v1' and new one as 'v1.1'

**Comment by wdzeng** [comment]
Ah. I'll update the log massage to eliminate this confusion.

**Comment by adamlui** [comment]
> You can look at the source code and you'll know this action is now using v1.1.

idk Actions architecture though

**Comment by adamlui** [comment]
> Ah. I'll update the log massage to eliminate this confusion.

but you said

> My opinion: v1 is the collection of v1.x, so v1 could be v1.0 or v1.1.

like it was not a log by you?

**Comment by adamlui** [comment]
I have to sleep but i'll try new secrets when I wake up

**Comment by adamlui** [comment]
But I doubt they expire so maybe there's a typo in your code

**Comment by adamlui** [comment]
API key expires after few months! Action is working again <3
