### ISSUE TITLE
API server responses with error code: 404

### ISSUE THREAD

**Issue by stcmz** [wdzeng/edge-addon#3]
Below is the GitHub Actions log
```
Run wdzeng/edge-addon@v1
Start edge addon action v1.0.3.
Start to publish edge addon.
Start to get access token.
Access token got.
Start to upload package.
Error: Edge Publish API server responses with error code: 404
Error: Request failed with status code 404
```
Here's the link https://github.com/stcmz/video-hotkeys/actions/runs/3512614835/jobs/5884504723

Any idea? The edge-addon action needs update?

**Comment by wdzeng** [comment]
> Below is the GitHub Actions log
> ```
> Run wdzeng/edge-addon@v1
> Start edge addon action v1.0.3.
> Start to publish edge addon.
> Start to get access token.
> Access token got.
> Start to upload package.
> Error: Edge Publish API server responses with error code: 404
> Error: Request failed with status code 404
> ```
> Here's the link https://github.com/stcmz/video-hotkeys/actions/runs/3512614835/jobs/5884504723
> 
> Any idea? The edge-addon action needs update?

Thanks for the report. I will look into it.

**Comment by wdzeng** [comment]
Your `product-id` is incorrect. According to the [Microsoft Edge Add-ons API Documentation](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#terminology):

```text
The product ID of the product whose draft needs to be published. The product ID is a 128-bit GUID that is associated with a product at Partner Center. For example: `d34f98f5-f9b7-42b1-bebb-98707202b21d`.
```

You may find the product ID at some management page.
