### ISSUE TITLE
An issue during publishing

### ISSUE THREAD

**Issue by akopachov** [wdzeng/edge-addon#7]
Hey, thanks for the great GH action!
I've been using it for half a year and it was working just fine. Today however I noticed that it started failing during the publishing update for the existing extension.

![image](https://github.com/user-attachments/assets/46340092-7017-4744-b35c-e6559714c2bb)

[Github workflow](https://github.com/akopachov/sveltab/actions/runs/10197653948/job/28210995264)

**Comment by wdzeng** [comment]
Hi @akopachov,

I was unable to reproduce the issue with my own extension. It appears this might be an ["irrecoverable failure"](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#response-when-the-publish-call-fails-with-an-irrecoverable-failure) as described in the Edge Add-ons API.

Unfortunately, I don't know how to fix it. I believe this is an error on Microsoft's side, and I suggest contacting their support team for assistance.

Thanks!

**Comment by wdzeng** [comment]
FYI I found [this](https://github.com/microsoft/MicrosoftEdge-Extensions/issues/175) bug. It was reported this bug as fixed at the end of July. I tested with my own extension just now and did not encounter an error.

**Comment by akopachov** [comment]
Thanks for checking! Awesome work!

**Comment by akopachov** [comment]
Indeed, it looks like it was something on Microsoft side. Today I tried to publish another update and it published [just fine](https://github.com/akopachov/sveltab/actions/runs/10303149267/job/28518547955).

So, @wdzeng, thanks again for a great github action! It works just fine.
