### ISSUE TITLE
v1.1 API support

### ISSUE THREAD

**Issue by XFox111** [wdzeng/edge-addon#8]
Microsoft recently released an updated version of Publishing API (https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?tabs=v1-1) and stated that they will be retiring v1 version sometime in the future.

**Comment by wdzeng** [comment]
Thanks for the reminder!

**Comment by wdzeng** [comment]
Working on then branch [features/api-v1.1](https://github.com/wdzeng/edge-addon/tree/features/api-v1.1).

**Comment by breadgrocery** [comment]
The date for ending v1 support seems due? The Microsoft Partner Center no longer displays the `Copy Access Token URL` button. 

And i got an error retrieving the access token from https://login.microsoftonline.com/5c9eedce-81bc-42f3-8823-48ba6258b391/oauth2/v2.0/token 

Any further progess on [features/api-v1.1](https://github.com/wdzeng/edge-addon/tree/features/api-v1.1) ？

**Comment by XFox111** [comment]
@breadgrocery I had the same issue recently. Try to issue a new access token. That did the trick for me

**Comment by XFox111** [comment]
@breadgrocery seems fine to me
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/80c84c25-e033-46ea-bb2c-98c94a1ab8db">

Could you perhaps accidentally enable v1.1? If so, there should be a button to revert back
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/4103c650-f020-499c-9560-46f1b0d1ab98">

EDIT: this also can be an issue with old API secrets. I had a similar one recently, and creating a new secret did the trick

**Comment by breadgrocery** [comment]
@XFox111 

<img width="1061" alt="Snipaste_2024-10-05_08-27-45" src="https://github.com/user-attachments/assets/b249deb7-4d70-494a-9634-b0df4ac9c222">

Nothing here and no `Revert Changes`

I registered very recently. I don't seem to have seen it , it seems to be mandatory to enable?

**Comment by XFox111** [comment]
> I registered very recently. I don't seem to have seen it , it seems to be mandatory to enable?

Yeah, looks like it. That's unfortunate that Microsoft decided to force new users to the new API, instead of giving them a choice

**Comment by wdzeng** [comment]
I will release the new version for v1.1 in a few hours 😱😱

**Comment by wdzeng** [comment]
I just released a new version of action that support API v1.1. @breadgrocery @XFox111 please try it 😄😄

```yaml
steps:
  - uses: wdzeng/edge-addon@v2
    with:
      product-id: your-addon-product-id
      zip-path: your-addon.zip
      api-key: ${{ secrets.API_KEY }}
      client-id: ${{ secrets.CLIENT_ID }}
```

**Comment by breadgrocery** [comment]
@wdzeng Thanks! v2 works!

**Comment by XFox111** [comment]
@wdzeng LGTM. Thanks :)
